name: Build WASM Distribution

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v13
      with:
        version: '3.1.45'
        actions-cache-folder: 'emsdk-cache'
        
    - name: Verify Emscripten installation
      run: |
        emcc --version
        em++ --version
        
    - name: Build WASM star demo
      run: |
        chmod +x build_wasm.sh
        ./build_wasm.sh
        
    - name: List generated files
      run: |
        ls -la dist/
        file dist/*
        
    - name: Upload WASM artifacts
      uses: actions/upload-artifact@v4
      with:
        name: canvas_ity_wasm_star_demo
        path: |
          dist/
        retention-days: 30
        
    - name: Deploy to GitHub Pages (if main branch)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        destination_dir: wasm-demo